import numpy as np
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('数组元素最大值：')
print(n.max())
print('数组中每一行的最大值：')
print(n.max(axis=0))
print('数组中每一列的最大值：')
print(n.max(axis=1))
print('数组元素最小值：')
print(n.min())
print('数组中每一行的最小值：')
print(n.min(axis=0))
print('数组中每一列的最小值：')
print(n.min(axis=1))